import { Listing, ListingCategory } from "../types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    title: "Luxury Beachfront Villa",
    description:
      "Stunning beachfront villa with amazing ocean views, private pool, and direct beach access. Perfect for family vacations.",
    owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    location: {
      address: "123 Beachfront Rd",
      city: "Malibu",
      state: "California",
      country: "USA",
      postalCode: "90265",
      lat: 34.025922,
      long: -118.779757,
    },
    images: [
      {
        id: "img1",
        url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
        alt: "Beachfront villa exterior",
      },
      {
        id: "img2",
        url: "https://images.unsplash.com/photo-1517541866997-ea18e32ea9e9",
        alt: "Beachfront villa pool",
      },
      {
        id: "img3",
        url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
        alt: "Beachfront villa interior",
      },
    ],
    pricePerNight: 850,
    currency: "USDC",
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
    amenities: [
      { id: "a1", name: "Pool", icon: "pool" },
      { id: "a2", name: "WiFi", icon: "wifi" },
      { id: "a3", name: "Kitchen", icon: "kitchen" },
      { id: "a4", name: "Free parking", icon: "local_parking" },
      { id: "a5", name: "Beach access", icon: "beach_access" },
    ],
    categories: [ListingCategory.BEACH, ListingCategory.VILLA],
    rating: 4.9,
    reviewCount: 48,
    createdAt: new Date("2023-01-10"),
    updatedAt: new Date("2023-05-15"),
    available: true,
  },
  {
    id: "2",
    title: "Mountain Cabin Retreat",
    description:
      "Cozy cabin nestled in the mountains with breathtaking views. Perfect for hiking enthusiasts and nature lovers.",
    owner: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
    location: {
      address: "456 Mountain Trail",
      city: "Aspen",
      state: "Colorado",
      country: "USA",
      postalCode: "81611",
      lat: 39.1911,
      long: -106.8175,
    },
    images: [
      {
        id: "img1",
        url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c",
        alt: "Mountain cabin exterior",
      },
      {
        id: "img2",
        url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
        alt: "Mountain view",
      },
      {
        id: "img3",
        url: "https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e",
        alt: "Cabin interior",
      },
    ],
    pricePerNight: 320,
    currency: "USDC",
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    amenities: [
      { id: "a1", name: "Fireplace", icon: "fireplace" },
      { id: "a2", name: "WiFi", icon: "wifi" },
      { id: "a3", name: "Kitchen", icon: "kitchen" },
      { id: "a4", name: "Free parking", icon: "local_parking" },
      { id: "a6", name: "Hiking trails", icon: "hiking" },
    ],
    categories: [ListingCategory.MOUNTAIN, ListingCategory.CABIN],
    rating: 4.8,
    reviewCount: 36,
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2023-06-10"),
    available: true,
  },
  {
    id: "3",
    title: "Modern Downtown Loft",
    description:
      "Stylish loft in the heart of downtown with easy access to restaurants, entertainment, and public transportation.",
    owner: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
    location: {
      address: "789 Urban St",
      city: "New York",
      state: "New York",
      country: "USA",
      postalCode: "10001",
      lat: 40.7128,
      long: -74.006,
    },
    images: [
      {
        id: "img1",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
        alt: "Modern loft interior",
      },
      {
        id: "img2",
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
        alt: "Loft living room",
      },
      {
        id: "img3",
        url: "https://images.unsplash.com/photo-1556912998-c57cc6b63cd7",
        alt: "Loft kitchen",
      },
    ],
    pricePerNight: 275,
    currency: "DAI",
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: [
      { id: "a2", name: "WiFi", icon: "wifi" },
      { id: "a3", name: "Kitchen", icon: "kitchen" },
      { id: "a7", name: "Air conditioning", icon: "ac_unit" },
      { id: "a8", name: "TV", icon: "tv" },
      { id: "a9", name: "Elevator", icon: "elevator" },
    ],
    categories: [ListingCategory.CITY, ListingCategory.APARTMENT],
    rating: 4.7,
    reviewCount: 52,
    createdAt: new Date("2023-03-20"),
    updatedAt: new Date("2023-07-05"),
    available: true,
  },
  {
    id: "4",
    title: "Countryside Farmhouse",
    description:
      "Charming farmhouse surrounded by rolling fields and countryside. Perfect for a peaceful getaway.",
    owner: "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
    location: {
      address: "101 Rural Route",
      city: "Woodstock",
      state: "Vermont",
      country: "USA",
      postalCode: "05091",
      lat: 43.6106,
      long: -72.5183,
    },
    images: [
      {
        id: "img1",
        url: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963",
        alt: "Farmhouse exterior",
      },
      {
        id: "img2",
        url: "https://images.unsplash.com/photo-1505916349660-8d91a99c3e23",
        alt: "Farmhouse interior",
      },
      {
        id: "img3",
        url: "https://images.unsplash.com/photo-1500076656116-558758c991c1",
        alt: "Countryside view",
      },
    ],
    pricePerNight: 195,
    currency: "USDT",
    maxGuests: 6,
    bedrooms: 3,
    beds: 4,
    baths: 2,
    amenities: [
      { id: "a1", name: "Fireplace", icon: "fireplace" },
      { id: "a2", name: "WiFi", icon: "wifi" },
      { id: "a3", name: "Kitchen", icon: "kitchen" },
      { id: "a4", name: "Free parking", icon: "local_parking" },
      { id: "a10", name: "Garden", icon: "grass" },
    ],
    categories: [ListingCategory.COUNTRYSIDE, ListingCategory.HOUSE],
    rating: 4.9,
    reviewCount: 28,
    createdAt: new Date("2023-04-05"),
    updatedAt: new Date("2023-08-20"),
    available: true,
  },
  {
    id: "5",
    title: "Unique Treehouse Experience",
    description:
      "Stay in a magical treehouse surrounded by nature. A truly unique experience for the adventurous traveler.",
    owner: "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65",
    location: {
      address: "42 Forest Path",
      city: "Portland",
      state: "Oregon",
      country: "USA",
      postalCode: "97204",
      lat: 45.5152,
      long: -122.6784,
    },
    images: [
      {
        id: "img1",
        url: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131",
        alt: "Treehouse exterior",
      },
      {
        id: "img2",
        url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
        alt: "Treehouse interior",
      },
      {
        id: "img3",
        url: "https://images.unsplash.com/photo-1533551037358-c8f7182cdb79",
        alt: "Forest view",
      },
    ],
    pricePerNight: 225,
    currency: "USDC",
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: [
      { id: "a2", name: "WiFi", icon: "wifi" },
      { id: "a11", name: "Outdoor shower", icon: "shower" },
      { id: "a12", name: "Hammock", icon: "weekend" },
      { id: "a13", name: "Eco-friendly", icon: "eco" },
    ],
    categories: [ListingCategory.UNIQUE, ListingCategory.COUNTRYSIDE],
    rating: 4.95,
    reviewCount: 42,
    createdAt: new Date("2023-05-15"),
    updatedAt: new Date("2023-09-01"),
    available: true,
  },
];
